try:
    int("maluco feio")
except(ValueError):
    print("funcao aplicada no localerrado")
